<a href="https://colab.research.google.com/github/abdurrahman16/NumPy/blob/main/Advance_Numpy_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
a= np.arange(24)

In [4]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [5]:
a.size

24

In [6]:
a.ndim

1

In [7]:
a=a.reshape(4,6)

In [8]:
a.ndim

2

In [9]:
a=a.reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
a.shape

(2, 3, 4)

In [11]:
a.dtype

dtype('int64')

In [15]:
d= np.arange(20, dtype=float)

In [17]:
d.dtype

dtype('float64')

In [18]:
print(d)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [19]:
d.itemsize

8