<a href="https://colab.research.google.com/github/abdurrahman16/NumPy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([2,3,4,6,8])
result =arr+arr1
print(result)

[ 3  5  7 10 13]


In [9]:
from numpy import random

In [7]:
test= random.rand()
print(test)

0.6384123493663799


In [14]:
test2= random.randint(1000, size=(5,5))
print(test2)

[[120  31 882 381  22]
 [314 832 630 788 811]
 [209 154 595   4 913]
 [452 481 113  44 896]
 [507 903 979 637 315]]
