<a href="https://colab.research.google.com/github/abdurrahman16/NumPy/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [22]:
mylist=[9,5,3,4]
nparray= np.array(mylist)
print(nparray)

[9 5 3 4]


In [21]:
type(nparray)

numpy.ndarray

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [34]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x= np.arange(2,11,2)

In [38]:
print(x)

[ 2  4  6  8 10]


In [39]:
type(x)

numpy.ndarray

In [54]:
d=np.linspace(2,10,50)
print(d)

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]


In [46]:
print(d[5])

2.816326530612245


In [48]:
np.random.rand(5,6)

array([[0.77783232, 0.86069919, 0.62464127, 0.98245833, 0.47458974,
        0.05001669],
       [0.67974621, 0.00330621, 0.48622548, 0.50443703, 0.47377195,
        0.81692307],
       [0.19342203, 0.94026722, 0.80884243, 0.37533062, 0.31756806,
        0.06799747],
       [0.63109455, 0.59145357, 0.07112304, 0.01198066, 0.16656417,
        0.19817493],
       [0.84261817, 0.23903555, 0.58179991, 0.87865202, 0.81709788,
        0.5695393 ]])

In [49]:
np.random.randn(5,6)

array([[ 0.86227274,  1.22280783,  0.48977493, -0.82358197, -2.20674254,
        -0.0160749 ],
       [ 0.40253328,  0.44434868,  0.62920973,  0.40576968, -1.17368521,
         0.44146583],
       [ 0.09252054, -0.60001185, -2.41693143, -0.14039759,  1.25160202,
         0.71732566],
       [ 0.32390962,  0.44938544, -0.33526033,  1.13065215,  0.74363774,
         0.21150762],
       [-1.20585272,  0.89504778, -1.07977707, -0.87478414, -0.28218101,
         0.68491341]])

In [52]:
np.random.randint(1,10,50)

array([7, 1, 1, 5, 8, 3, 5, 6, 3, 5, 7, 1, 8, 8, 6, 5, 8, 5, 4, 9, 5, 7,
       8, 4, 7, 3, 3, 8, 1, 8, 5, 4, 2, 1, 4, 5, 4, 5, 6, 7, 1, 6, 2, 5,
       4, 2, 2, 2, 5, 5])

In [55]:
np.random.seed(42)
np.random.randint(1,101,(2,5))

array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75]])