<a href="https://colab.research.google.com/github/abdurrahman16/NumPy/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [22]:
mylist=[9,5,3,4]
nparray= np.array(mylist)
print(nparray)

[9 5 3 4]


In [21]:
type(nparray)

numpy.ndarray

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])