<a href="https://colab.research.google.com/github/abdurrahman16/NumPy/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [189]:
import numpy as np

In [190]:
mylist=[9,5,3,4]
nparray= np.array(mylist)
print(nparray)

[9 5 3 4]


In [191]:
type(nparray)

numpy.ndarray

In [192]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [193]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [194]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [195]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [196]:
x= np.arange(2,11,2)

In [197]:
print(x)

[ 2  4  6  8 10]


In [198]:
type(x)

numpy.ndarray

In [199]:
d=np.linspace(2,10,50)
print(d)

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]


In [200]:
print(d[5])

2.816326530612245


In [201]:
np.random.rand(5,6)

array([[0.18182497, 0.18340451, 0.30424224, 0.52475643, 0.43194502,
        0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
        0.78517596],
       [0.19967378, 0.51423444, 0.59241457, 0.04645041, 0.60754485,
        0.17052412],
       [0.06505159, 0.94888554, 0.96563203, 0.80839735, 0.30461377,
        0.09767211],
       [0.68423303, 0.44015249, 0.12203823, 0.49517691, 0.03438852,
        0.9093204 ]])

In [202]:
np.random.randn(5,6)

array([[ 0.82254491, -1.22084365,  0.2088636 , -1.95967012, -1.32818605,
         0.19686124],
       [ 0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
        -0.71984421],
       [-0.46063877,  1.05712223,  0.34361829, -1.76304016,  0.32408397,
        -0.38508228],
       [-0.676922  ,  0.61167629,  1.03099952,  0.93128012, -0.83921752,
        -0.30921238],
       [ 0.33126343,  0.97554513, -0.47917424, -0.18565898, -1.10633497,
        -1.19620662]])

In [203]:
np.random.randint(1,10,50)

array([3, 8, 6, 3, 1, 3, 5, 3, 1, 5, 7, 7, 9, 3, 7, 1, 4, 4, 5, 7, 7, 4,
       7, 3, 6, 2, 9, 5, 6, 4, 7, 9, 7, 1, 1, 9, 9, 4, 9, 3, 7, 6, 8, 9,
       5, 1, 3, 8, 6, 8])

In [204]:
np.random.seed(42)
np.random.randint(1,101,(2,5))

array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75]])

In [205]:
testarr=np.arange(1,21)
print(testarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [206]:
testarr.shape

(20,)

In [207]:
testarr.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [212]:
newarr= np.random.randint(1,100,10)
print(newarr)

[64 60 21 33 76 58 22 89 49 91]


In [213]:
newarr.max()

np.int64(91)

In [214]:
newarr.min()

np.int64(21)

In [215]:
newarr.argmax()

np.int64(9)